# Generated by Django 3.2.9 on 2021-11-10 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=254, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now=True, verbose_name='Start work in')),
                ('end_datetime', models.DateTimeField(auto_now=True, verbose_name='End work in')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.project', verbose_name='Project')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.worker', verbose_name='Worker')),
            ],
        ),
    ]
