# Generated by Django 3.2.9 on 2021-11-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_worklog_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start work in'),
        ),
    ]
